name: Quality

on:
  push:
    paths:
      - src/**
      - .github/workflows/quality.yml

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JoostWG/actions/npm@master

      - name: Run ESLint
        run: npx eslint .

  dprint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JoostWG/actions/npm@master

      - name: Run dprint
        run: npx dprint check

  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JoostWG/actions/npm@master

      - name: Run TypeScript
        run: npx tsc --noEmit

  jest:
    runs-on: ubuntu-latest
    needs: typescript

    steps:
      - uses: actions/checkout@v4

      - uses: JoostWG/actions/npm@master

      - name: Run Jest
        run: npx jest

  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v8
